friendster = loadgraph("$GRAPE_LIB/grape-test/tianhe/fs-64-u.yaml")
gggmc = loadapp("$GRAPE_LIB/GGGMC.yaml")

gggmc.query(64 5000000 65608366 1800000000 0.1 0.95 ./grape-test/sources-64.txt, "im")

unloadapp(gggmc)
unloadgraph(friendster)
exit
